import AppBar from "@/components/AppBar";
import "./globals.css";
import Providers from "@/components/Providers";

// add bootstrap css 
import 'bootstrap/dist/css/bootstrap.css'
// own css files here
// import "../css/customcss.css";

export const metadata = {
  title: "Next-Auth Tutorial",
  description: "Generated by Garri Dev",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppBar />
          
          <button type="button" className="btn btn-primary" data-bs-toggle="modal"data-bs-target="#exampleModal"
      >
        <h1>Esto esta es un h1 en src/layout</h1>
      </button>
          {children}
        </Providers>
      </body>
    </html>
  );
}
